apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-monitor
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
      nodePort: 30093
  selector:
    k8s-app: alertmanager
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-ingress
  namespace: kube-monitor
spec:
  rules:
  - host: alertmanager.cloudnative.ies.inventec
    http:
      paths:
      - backend:
          serviceName: alertmanager
          servicePort: 80
