apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-monitor
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'mailrelay-b.ies.inventec:25'
      smtp_from: 'prometheus-alertmanager@inventec.com'
      smtp_auth_username: 'xxxxxxxxxxxxxxxxxx'
      smtp_auth_password: 'xxxxxxxxxxxxxxxxxx'
      smtp_hello: 'ies.inventec'
      smtp_require_tls: false
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
      receiver: default
      #routes:
      #- receiver: email
      #  group_wait: 10s
      #  match:
      #    team: node
    receivers:
    - name: 'default'
      email_configs:
      - to: 'chang.jay@inventec.com, Chiang.Keith@inventec.com, Liu.AllenJH@inventec.com, Wu.Wade@inventec.com, Fan.Tian-yuan@inventec.com.cn'
        send_resolved: true
      webhook_configs:
      - url: 'http://10.99.104.251:1990/api/v1/wechat-bot/alert-manager'
        send_resolved: true
   # - name: 'email'
   #   email_configs:
   #   - to: 'chang.jay@inventec.com, Chiang.Keith@inventec.com, Liu.AllenJH@inventec.com, Wu.Wade@inventec.com, Fan.Tian-yuan@inventec.com.cn'
   #     send_resolved: true
   #   webhook_configs:
   #   - url: 'http://10.99.104.251:1990/api/v1/wechat-bot/alert-manager'
   #     send_resolved: true
