apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: kube-monitor
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "Prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "prometheus.kube-monitor.svc.cluster.local:9090",
                "version": 1
            }
        ]
    }

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
  namespace: kube-monitor
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gluster-cluster"
    path: "grafana_data"
    readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data
  namespace: kube-monitor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: kube-monitor
  labels:
    app: grafana
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        component: core
    spec:
      containers:
      - image: registry.ipt-gitlab:8081/sit-develop-tool/ipt-microservice-monitoring/grafana:__VERSION__
        name: grafana
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        env:
          - name: GF_INSTALL_PLUGINS
            value: "michaeldmoore-multistat-panel, grafana-piechart-panel"
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
          - name: GF_SECURITY_ADMIN_USER
            value: "admin"
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "admin"
          - name: GF_SECURITY_ALLOW_EMBEDDING
            value: "true"
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: tz-config
          mountPath: /etc/localtime
      securityContext:
        runAsUser: 0
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-data
      - name: grafana-datasources
        configMap:
            defaultMode: 420
            name: grafana-datasources
      imagePullSecrets:
      - name: gitlab-registry

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-monitor
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30092

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: kube-monitor
spec:
  rules:
  - host: grafana.cloudnative.ies.inventec
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
