---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: kube-monitor
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30003
  selector:
    app: prometheus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: kube-monitor
spec:
  rules:
  - host: prometheus.cloudnative.ies.inventec
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
